StudentTestingSystem/Areas/Admin/Models/Subject/SubjectIndexViewModel.cs
using StudentTestingSystem.Services.Extensions;
using StudentTestingSystem.Services.TransportModels.Admin.Subject.Response;
using System.Collections.Generic;

namespace StudentTestingSystem.Areas.Admin.Models.Subject
{
    public class SubjectIndexViewModel
    {
        public IEnumerable<SubjectResponse> Subjects { get; set; }
        public PageInfo<SubjectResponse> PageInfo { get; set; }
        public List<Breadcrumb> Breadcrumb { get; set; }
    }
}

StudentTestingSystem/Areas/Admin/Controllers/SubjectController.cs
using StudentTestingSystem.Areas.Admin.Models.Subject;
using StudentTestingSystem.Services.Abstract.Admin;
using StudentTestingSystem.Services.Extensions;
using StudentTestingSystem.Services.TransportModels.Admin.Subject.Request;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using StudentTestingSystem.Services.Abstract.SuperAdmin;
using StudentTestingSystem.Areas.Admin.Models;
using System.Collections.Generic;

namespace StudentTestingSystem.Areas.Admin.Controllers
{
    [Route("Admin/[controller]/[action]")]
    public class SubjectController : BaseController
    {
        private readonly ISubjectAdminService _subjectAdminService;
        private readonly IProfileSuperAdminService _profileSuperAdminService;
        
        public SubjectController(
            ISubjectAdminService subjectAdminService,
            IProfileSuperAdminService profileSuperAdminService)
        {
            _subjectAdminService = subjectAdminService;
            _profileSuperAdminService = profileSuperAdminService;
        }

        // GET: Admin/Subject/Index
        [Authorize(Roles = "SuperAdmin, Admin")]
        public async Task<ActionResult> Index(int page = 1, int pageSize = 10)
        {
            if (IsUserExistInRole("SuperAdmin"))
            {
                return RedirectToAction("Index", "Subject", new { Area = "SuperAdmin" });
            }

            var userId = GetCurrentUserId();
            var profile = await _profileSuperAdminService.GetProfileByUserIdAsync(userId);
            var subjects = await _subjectAdminService.GetAllSubjectsByUserProfileId(page, pageSize, profile.Id);

            List<Breadcrumb> breadcrumb = new List<Breadcrumb>() {
                new Breadcrumb("Home", "Index", "Home", new { Area = "" }),
                new Breadcrumb("Subjects")
            };

            SubjectIndexViewModel subjectIndexViewModel = new SubjectIndexViewModel
            {
                PageInfo = subjects,
                Subjects = subjects.Results,
                Breadcrumb = breadcrumb
            };

            ViewBag.Title = "Subject list";
            return View(subjectIndexViewModel);
        }

        // GET: Admin/Subject/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.Title = "Add a new subject";
            return View(new CreateSubjectRequest());
        }

        // POST: Admin/Subject/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateSubjectRequest model)
        {
            if (ModelState.IsValid)
            {
                model.UserId = GetCurrentUserId();
                await _subjectAdminService.CreateSubjectAsync(model);
                return RedirectToAction("Index");
            }
            ViewBag.Title = "Add a new subject";
            return View(model);
        }

        // GET: Admin/Subject/Edit
        [Authorize(Roles = "SuperAdmin, Admin")]
        public async Task<ActionResult> Edit(Guid id)
        {
            var subject = await _subjectAdminService.GetSubjectByIdAsync(id);
            EditSubjectRequest editSubjectRequest = subject.ToEditSubjectRequest();

            ViewBag.Title = $"Edit subject \"{subject.Title}\"";
            return View(editSubjectRequest);
        }

        // POST: Admin/Subject/Edit
        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditSubjectRequest model)
        {
            if (ModelState.IsValid)
            {
                await _subjectAdminService.EditSubjectAsync(model);
                return RedirectToAction("Index");
            }
            ViewBag.Title = "Edit subject";
            return View(model);
        }

        // POST: Admin/Subject/Delete
        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpPost]
        public async Task Delete(Guid id)
        {
            await _subjectAdminService.DeleteSubjectAsync(id);
        }

        // GET: Admin/Subject/Details
        public async Task<ActionResult> Details(Guid id)
        {
            var subject = await _subjectAdminService.GetSubjectByIdAsync(id);

            ViewBag.Title = $"Details of the subject \"{subject.Title}\"";
            return View(subject);
        }
    }
}

StudentTestingSystem/Areas/Admin/Controllers/ThemeController.cs
using StudentTestingSystem.Areas.Admin.Models;
using StudentTestingSystem.Areas.Admin.Models.Theme;
using StudentTestingSystem.Services.Abstract.Admin;
using StudentTestingSystem.Services.Extensions;
using StudentTestingSystem.Services.TransportModels.Admin.Theme.Request;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace StudentTestingSystem.Areas.Admin.Controllers
{
    [Route("Admin/[controller]/[action]")]
    public class ThemeController : Controller
    {
        private readonly ISubjectAdminService _subjectAdminService;
        private readonly IThemeAdminService _themeAdminService;

        public ThemeController(
            IThemeAdminService themeAdminService,
            ISubjectAdminService subjectAdminService)
        {
            _themeAdminService = themeAdminService;
            _subjectAdminService = subjectAdminService;
        }

        // GET: Admin/Theme/Index
        [Authorize(Roles = "SuperAdmin, Admin")]
        public async Task<ActionResult> Index(Guid subjectId, int page = 1, int pageSize = 10)
        {
            var themes = await _themeAdminService.GetAllThemesBySubjectId(subjectId, page, pageSize);
            var subject = await _subjectAdminService.GetSubjectByIdAsync(subjectId);

            List<Breadcrumb> breadcrumb = new List<Breadcrumb>() {
                new Breadcrumb("Home", "Index", "Home", new { Area = "" }),
                new Breadcrumb("Subjects", "Index", "Subject", new { Area = "Admin" }),
                new Breadcrumb("Subject themes")
            };

            ThemeIndexViewModel themeIndexViewModel = new ThemeIndexViewModel
            {
                PageInfo = themes,
                SubjectId = subjectId,
                Themes = themes.Results,
                Breadcrumb = breadcrumb
            };

            ViewBag.Title = $"List of themes in subject \"{subject.Title}\"";
            return View(themeIndexViewModel);
        }

        // GET: Admin/Theme/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Guid subjectId)
        {
            CreateThemeRequest createThemeRequest = new CreateThemeRequest()
            {
                SubjectId = subjectId,
                TimeLine = 1
            };
            ViewBag.Title = "Add a new theme";
            return View(createThemeRequest);
        }

        // POST: Admin/Theme/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateThemeRequest model)
        {
            if (ModelState.IsValid)
            {
                await _themeAdminService.CreateThemeAsync(model);
                return RedirectToAction("Index", new { subjectId = model.SubjectId });
            }
            ViewBag.Title = "Add a new theme";
            return View(model);
        }

        // GET: Admin/Theme/Edit
        [Authorize(Roles = "SuperAdmin, Admin")]
        public async Task<ActionResult> Edit(Guid id)
        {
            var theme = await _themeAdminService.GetThemeByIdAsync(id);
            EditThemeRequest editThemeRequest = theme.ToEditThemeRequest();
            ViewBag.Title = $"Edit theme \"{theme.Title}\"";
            return View(editThemeRequest);
        }

        // POST: Admin/Theme/Edit
        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditThemeRequest model)
        {
            if (ModelState.IsValid)
            {
                await _themeAdminService.EditThemeAsync(model);
                return RedirectToAction("Index", new { subjectId = model.SubjectId });
            }
            ViewBag.Title = "Edit theme";
            return View(model);
        }

        // POST: Admin/Theme/Delete
        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpPost]
        public async Task Delete(Guid id)
        {
            await _themeAdminService.DeleteThemeAsync(id);
        }
    }
}

StudentTestingSystem/Areas/Student/Controllers/SubjectController.cs
using StudentTestingSystem.Areas.Admin.Controllers;
using StudentTestingSystem.Areas.Admin.Models;
using StudentTestingSystem.Areas.Admin.Models.Subject;
using StudentTestingSystem.Services.Abstract.Admin;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace StudentTestingSystem.Areas.Student.Controllers
{
    [Route("Student/[controller]/[action]")]
    public class SubjectController : BaseController
    {
        private readonly ISubjectAdminService _subjectAdminService;

        public SubjectController(ISubjectAdminService subjectAdminService)
        {
            _subjectAdminService = subjectAdminService;
        }

        // GET: Student/Subject
        [Authorize(Roles = "User")]
        public async Task<ActionResult> Index(int page = 1, int pageSize = 10)
        {
            var subjects = await _subjectAdminService.GetAllSubjects(page, pageSize);

            var breadcrumb = new List<Breadcrumb>
            {
                new Breadcrumb("Home", "Index", "Home", new { Area = "" }),
                new Breadcrumb("Subjects")
            };

            SubjectIndexViewModel subjectIndexViewModel = new SubjectIndexViewModel
            {
                PageInfo = subjects,
                Subjects = subjects.Results,
                Breadcrumb = breadcrumb
            };

            ViewBag.Title = "Subject list";
            return View(subjectIndexViewModel);
        }
    }
}

StudentTestingSystem/Areas/SuperAdmin/Controllers/SubjectController.cs
using StudentTestingSystem.Areas.Admin.Models;
using StudentTestingSystem.Areas.Admin.Models.Subject;
using StudentTestingSystem.Services.Abstract.Admin;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace StudentTestingSystem.Areas.SuperAdmin.Controllers
{
    [Route("SuperAdmin/[controller]/[action]")]
    public class SubjectController : Controller
    {
        private readonly ISubjectAdminService _subjectAdminService;

        public SubjectController(ISubjectAdminService subjectAdminService)
        {
            _subjectAdminService = subjectAdminService;
        }

        // GET: Student/Subject
        [Authorize(Roles = "SuperAdmin")]
        public async Task<ActionResult> Index(int page = 1, int pageSize = 10)
        {
            var subjects = await _subjectAdminService.GetAllSubjects(page, pageSize);

            var breadcrumb = new List<Breadcrumb>
            {
                new Breadcrumb("Home", "Index", "Home", new { Area = "" }),
                new Breadcrumb("Subjects")
            };

            SubjectIndexViewModel subjectIndexViewModel = new SubjectIndexViewModel
            {
                PageInfo = subjects,
                Subjects = subjects.Results,
                Breadcrumb = breadcrumb
            };

            ViewBag.Title = "Subject list";
            return View(subjectIndexViewModel);
        }
    }
}

StudentTestingSystem/Areas/SuperAdmin/Views/Subject/Index.cshtml
@model StudentTestingSystem.Areas.Admin.Models.Subject.SubjectIndexViewModel
@using StudentTestingSystem.Helpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_Breadcrumb", Model.Breadcrumb)

@if (!Model.Subjects.Any())
{
    <div class="row">
        <div class="col-md-12">
            <div class="card ">
                <div class="card-header ">
                    <h5 class="card-title">@ViewBag.Title</h5>
                </div>
                <div class="card-body ">
                    <div class="alert alert-warning" role="alert">There are no subjects in the system.</div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-md-12">
            <div class="card ">
                <div class="card-header ">
                    <h5 class="card-title">@ViewBag.Title</h5>
                </div>
                <div class="card-body ">
                    <div class="table-responsive">
                        <table class="table">
                            <thead class=" text-primary">
                                <th class="text-center">Subject</th>
                                <th class="text-center">Teacher</th>
                                <th class="text-center">Themes</th>
                                <th class="text-center">Actions</th>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Subjects)
                                {
                                    <tr>
                                        <td>@Html.ActionLink(item.Title, "Details", "Subject", new { Area = "Admin", id = item.Id }, null)</td>
                                        <td class="text-center">@Html.DisplayFor(modelItem => item.UserName)</td>
                                        <td class="text-center">@Html.DisplayFor(modelItem => item.ThemesCount)</td>
                                        <td class="text-center">
                                            @Html.ActionLink("Themes", "Index", "Theme", new { Area = "Admin", subjectId = item.Id }, new { @class = "btn btn-success" })
                                            @Html.ActionLink("Edit", "Edit", "Subject", new { Area = "Admin", id = item.Id }, new { @class = "btn btn-primary" })
                                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-item-id="@item.Id" data-item-description="@item.Title">Delete</button>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div id="paginationFooter" class="card-footer ">
                    <hr>
                    <div class="stats">
                        @Html.PageLinks(Model.PageInfo, x => Url.Action("Index", new { page = x }))
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Confirm delete</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to delete: <span class="description-item"></span></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" value="Delete" class="btn btn-danger btn-ok" />
                </div>
            </div>
        </div>
    </div>

    <script>
        $('#deleteModal').on('click', '.btn-ok', function (e) {
            $.post('/Admin/Subject/Delete/' + $(this).data('itemId')).then(function () {
                window.location.href = '@Url.Action("Index", "Subject")';
            });
        });

        $('#deleteModal').on('show.bs.modal', function (e) {
            var data = $(e.relatedTarget).data();
            $('.description-item', this).text(data.itemDescription);
            $('.btn-ok', this).data('itemId', data.itemId);
        });
    </script>
}

<script>
    $("#subjectMenuItem").addClass("active");
</script>